import { Court, CourtPhotoRef, REQUIRED_PHOTO_STEPS } from "./types";
import { slugify } from "./slug";
import { orderPhotos } from "./photos";

function photos(hoops: number): CourtPhotoRef[] {
  return orderPhotos(
    REQUIRED_PHOTO_STEPS.filter((s) => !(hoops < 2 && s.kind === "kosz-b")).map((s) => ({
      kind: s.kind,
      caption: s.title,
    }))
  );
}

type Seed = Omit<Court, "photos" | "slug"> & { slug?: string };

const raw: Seed[] = [
  {
    id: "c1",
    name: "Pole Mokotowskie",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    lat: 52.2119,
    lng: 20.995,
    type: "otwarty",
    surface: "poliuretan",
    hoops: 2,
    lit: true,
    fenced: true,
    access: "24h",
    hours: "całą dobę",
    likes: 412,
    basketApproved: true,
    addedBy: "kuba_h",
    addedAt: "2026-04-11",
    description:
      "Pełnowymiarowa płyta w środku parku. Nowy poliuretan położony w 2024, linie wyraźne, obręcze z siatkami łańcuchowymi. Wieczorami komplet — trzeba czekać na wygraną.",
    seed: 11,
  },
  {
    id: "c2",
    name: "Park Skaryszewski",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    lat: 52.245,
    lng: 21.053,
    type: "streetball",
    surface: "asfalt",
    hoops: 2,
    lit: false,
    fenced: false,
    access: "24h",
    hours: "całą dobę",
    likes: 168,
    basketApproved: false,
    addedBy: "mateo",
    addedAt: "2026-05-02",
    description:
      "Klasyczny streetball pod drzewami. Asfalt miejscami popękany, ale kosze równe i zawsze ktoś gra.",
    seed: 27,
  },
  {
    id: "c3",
    name: "Hala OSiR Ochota",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    lat: 52.2135,
    lng: 20.9705,
    type: "kryty",
    surface: "parkiet",
    hoops: 2,
    lit: true,
    fenced: false,
    access: "godziny",
    hours: "07:00 - 22:00",
    likes: 96,
    basketApproved: false,
    addedBy: "ola.b",
    addedAt: "2026-03-19",
    description:
      "Parkiet w dobrym stanie, regulowane kosze, wstęp na godziny po rezerwacji. Zimą ratunek.",
    seed: 42,
  },
  {
    id: "c4",
    name: "Park Jordana",
    city: "Kraków",
    voivodeship: "małopolskie",
    lat: 50.063,
    lng: 19.92,
    type: "otwarty",
    surface: "poliuretan",
    hoops: 2,
    lit: true,
    fenced: true,
    access: "godziny",
    hours: "06:00 - 22:00",
    likes: 287,
    basketApproved: true,
    addedBy: "kuba_h",
    addedAt: "2026-04-28",
    description:
      "Poliuretan pod nogami, ogrodzone, oświetlone do 22. Jedno z najlepiej utrzymanych boisk w Krakowie.",
    seed: 8,
  },
  {
    id: "c5",
    name: "Zalew Nowohucki",
    city: "Kraków",
    voivodeship: "małopolskie",
    lat: 50.0402,
    lng: 20.0468,
    type: "streetball",
    surface: "beton",
    hoops: 1,
    lit: false,
    fenced: false,
    access: "24h",
    hours: "całą dobę",
    likes: 74,
    basketApproved: false,
    addedBy: "nowa_huta_ball",
    addedAt: "2026-06-07",
    description:
      "Jeden kosz nad wodą. Beton szorstki, obręcz bez siatki — miejsce na spokojne rzucanie o zachodzie.",
    seed: 63,
  },
  {
    id: "c6",
    name: "Zaspa",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    lat: 54.39,
    lng: 18.61,
    type: "otwarty",
    surface: "poliuretan",
    hoops: 2,
    lit: true,
    fenced: true,
    access: "24h",
    hours: "całą dobę",
    likes: 331,
    basketApproved: false,
    addedBy: "trojmiasto_hoops",
    addedAt: "2026-02-14",
    description:
      "Boisko między blokami z murralami w tle. Nawierzchnia jak nowa, kosze na regulowanej wysokości.",
    seed: 15,
  },
  {
    id: "c7",
    name: "Brzeźno — przy plaży",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    lat: 54.4051,
    lng: 18.6304,
    type: "streetball",
    surface: "asfalt",
    hoops: 2,
    lit: false,
    fenced: true,
    access: "24h",
    hours: "całą dobę",
    likes: 142,
    basketApproved: false,
    addedBy: "seaside",
    addedAt: "2026-05-21",
    description:
      "200 metrów od morza. Piach nanoszony na nawierzchnię, ale widok nie do pobicia.",
    seed: 31,
  },
  {
    id: "c8",
    name: "Cytadela",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    lat: 52.4231,
    lng: 16.9351,
    type: "otwarty",
    surface: "beton",
    hoops: 2,
    lit: false,
    fenced: false,
    access: "24h",
    hours: "całą dobę",
    likes: 205,
    basketApproved: false,
    addedBy: "pzn_baller",
    addedAt: "2026-01-30",
    description:
      "Betonowa płyta na skarpie parku. Twarde podłoże, ale kosze porządne i zawsze wolne rano.",
    seed: 55,
  },
  {
    id: "c9",
    name: "Malta — kompleks",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    lat: 52.4019,
    lng: 16.9797,
    type: "otwarty",
    surface: "plytki",
    hoops: 2,
    lit: true,
    fenced: true,
    access: "godziny",
    hours: "08:00 - 21:00",
    likes: 118,
    basketApproved: false,
    addedBy: "ola.b",
    addedAt: "2026-06-18",
    description:
      "Dwa pełne boiska obok siebie przy jeziorze. Wieczorem oświetlenie ledowe.",
    seed: 72,
  },
  {
    id: "c10",
    name: "Wyspa Słodowa",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    lat: 51.1153,
    lng: 17.0351,
    type: "streetball",
    surface: "beton",
    hoops: 1,
    lit: true,
    fenced: false,
    access: "24h",
    hours: "całą dobę",
    likes: 264,
    basketApproved: true,
    addedBy: "wro_street",
    addedAt: "2026-03-05",
    description:
      "Legendarny kosz na wyspie. Jeden kosz, zero ogrodzenia, maksimum klimatu — latem gra się do północy.",
    seed: 3,
  },
  {
    id: "c11",
    name: "Park Południowy",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    lat: 51.09,
    lng: 17.02,
    type: "otwarty",
    surface: "asfalt",
    hoops: 2,
    lit: false,
    fenced: true,
    access: "godziny",
    hours: "07:00 - 21:00",
    likes: 61,
    basketApproved: false,
    addedBy: "mateo",
    addedAt: "2026-07-02",
    description: "Spokojne boisko w cieniu, dobre na trening rzutowy.",
    seed: 47,
  },
  {
    id: "c12",
    name: "Dolina Trzech Stawów",
    city: "Katowice",
    voivodeship: "śląskie",
    lat: 50.245,
    lng: 19.04,
    type: "otwarty",
    surface: "poliuretan",
    hoops: 2,
    lit: true,
    fenced: true,
    access: "24h",
    hours: "całą dobę",
    likes: 193,
    basketApproved: false,
    addedBy: "slask_ball",
    addedAt: "2026-04-03",
    description:
      "Nowy kompleks sportowy w parku. Poliuretan, trybunki, ławki, woda w kranie obok.",
    seed: 19,
  },
  {
    id: "c13",
    name: "Park Poniatowskiego",
    city: "Łódź",
    voivodeship: "łódzkie",
    lat: 51.75,
    lng: 19.44,
    type: "streetball",
    surface: "asfalt",
    hoops: 2,
    lit: false,
    fenced: false,
    access: "24h",
    hours: "całą dobę",
    likes: 88,
    basketApproved: false,
    addedBy: "lodz_hoops",
    addedAt: "2026-05-30",
    description: "Stary asfalt, nowe tablice. Miejsce z historią.",
    seed: 36,
  },
  {
    id: "c14",
    name: "Jasne Błonia",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    lat: 53.438,
    lng: 14.54,
    type: "otwarty",
    surface: "syntetyk",
    hoops: 2,
    lit: true,
    fenced: true,
    access: "godziny",
    hours: "08:00 - 22:00",
    likes: 57,
    basketApproved: false,
    addedBy: "szczecin_ball",
    addedAt: "2026-06-25",
    description: "Boisko wielofunkcyjne, nawierzchnia syntetyczna, siatki nowe.",
    seed: 81,
  },
  {
    id: "c15",
    name: "Zalew Zemborzycki",
    city: "Lublin",
    voivodeship: "lubelskie",
    lat: 51.19,
    lng: 22.53,
    type: "otwarty",
    surface: "beton",
    hoops: 2,
    lit: false,
    fenced: false,
    access: "24h",
    hours: "całą dobę",
    likes: 44,
    basketApproved: false,
    addedBy: "lbn",
    addedAt: "2026-07-14",
    description: "Nad wodą, blisko plaży miejskiej. Beton, ale równy.",
    seed: 24,
  },
  {
    id: "c16",
    name: "Planty",
    city: "Białystok",
    voivodeship: "podlaskie",
    lat: 53.13,
    lng: 23.16,
    type: "otwarty",
    surface: "poliuretan",
    hoops: 2,
    lit: true,
    fenced: true,
    access: "godziny",
    hours: "07:00 - 22:00",
    likes: 39,
    basketApproved: false,
    addedBy: "podlasie",
    addedAt: "2026-07-20",
    description: "Świeżo wyremontowane, poliuretan i porządne tablice.",
    seed: 68,
  },
  {
    id: "c17",
    name: "Hala Millenium",
    city: "Rzeszów",
    voivodeship: "podkarpackie",
    lat: 50.0413,
    lng: 21.999,
    type: "kryty",
    surface: "parkiet",
    hoops: 2,
    lit: true,
    fenced: false,
    access: "ograniczony",
    hours: "16:00 - 21:00 (pn-pt)",
    likes: 31,
    basketApproved: false,
    addedBy: "rze",
    addedAt: "2026-08-01",
    description: "Hala przyszkolna, otwarta popołudniami po zgłoszeniu.",
    seed: 90,
  },
  {
    id: "c18",
    name: "Nad Łyną",
    city: "Olsztyn",
    voivodeship: "warmińsko-mazurskie",
    lat: 53.7784,
    lng: 20.4801,
    type: "streetball",
    surface: "beton",
    hoops: 1,
    lit: false,
    fenced: false,
    access: "24h",
    hours: "całą dobę",
    likes: 22,
    basketApproved: false,
    addedBy: "wm_street",
    addedAt: "2026-08-05",
    description: "Pojedynczy kosz nad rzeką, idealny na poranne rzucanie.",
    seed: 52,
  },
];

export const COURTS: Court[] = raw.map((c) => ({
  ...c,
  slug: c.slug ?? `${slugify(c.city)}-${slugify(c.name)}`,
  photos: photos(c.hoops),
}));

export function getCourt(slug: string): Court | undefined {
  return COURTS.find((c) => c.slug === slug);
}
